### PR TITLE
UvA DL Tutorials: Update API to PL 1.8

### PR DESCRIPTION
**Pull request by phlippe**
## What does this PR do?

In the UvA DL Tutorial 8 (Deep Autoencoder), the generation callback used a deprecated and now removed API of `on_epoch_end`. This pull request updates it to `on_train_epoch_end` to be compatible with the new PL 1.8 version.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@phlippe seems we have finally fixed the ci/cd and so we are fine to proceed... :rabbit:

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
btw, shall we in such a case also bump the min version? :otter:

**Comment by phlippe** [comment]
Thanks @Borda for fixing the CI and merging the pull request! 
Pushing up the minimum version sounds good, I noticed that the notebooks are still using `progress_bar_refresh_rate` which also became deprecated lately in Lightning. I will send another pull request with this update, then all notebooks should run smoothly with the newest Lightning version

**Comment by Borda** [comment]
@phlippe shall we bump all classes to use PL 1.8 as minimal version? What do you think?

**Comment by phlippe** [comment]
Yes, agreed, there have been a few API changes since 1.4 which would be good to enforce with 1.8 (e.g. accelerator selection and progress bar). I think we may have to merge #222 beforehand though

**Pull request merged**
