### PR TITLE
UvA DL Tutorials: Updating PL API to >1.8

### PR DESCRIPTION
**Pull request by phlippe**
## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

## What does this PR do?

Updates notebooks to PL 1.8 in terms of:
* progress bar API (replace `progress_bar_refresh_rate` by `enable_progress_bar`)
* accelerator selection (replace `gpus` by `accelerator` and `devices`)

Fixes typo in `torch.backends.cudnn.deterministic`

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by phlippe** [comment]
Remaining problems:
* Tutorial 10 (PixelCNN) runs out of time in the sampling step although GPU should be deployed. Is there any issue with the testing there?
* Tutorial 13 (SimCLR) seems to run out of memory or time when downloading STL10
* Tutorial 6 (GNNs) has troubles installing pytorch geometric, also on Colab. Seems to be missing pip find link?

**Review by Borda — APPROVED** [review]
let's add to all meta PL >= 1.8 because this may not be compatible with older versions

**Comment by Borda** [comment]
interesting error, not sure where it came from...
```
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[22], line 2
      1 pl.seed_everything(1)
----> 2 samples = model.sample(img_shape=(8, 1, 64, 64))
      3 show_imgs(samples.cpu())
```

**Comment by phlippe** [comment]
The output on Azure suggests it is running out of time:

```
=================================== FAILURES ===================================
_ course_UvA-DL/10-autoregressive-image-modeling/Autoregressive_Image_Modeling.ipynb::Cell 21 _
Notebook cell execution failed
Cell 21: Timeout of 300 seconds exceeded executing cell

Input:
pl.seed_everything(1)
samples = model.sample(img_shape=(8, 1, 64, 64))
show_imgs(samples.cpu())
```

I don't know why it runs out of time now, since it didn't have any problems beforehand. For this notebook, it may be ok to comment out the line since this is just for showing samples, but Tutorial 13 (SimCLR) runs already out of time when downloading the dataset:

```
=================================== FAILURES ===================================
__________ course_UvA-DL/13-contrastive-learning/SimCLR.ipynb::Cell 5 __________
Notebook cell execution failed
Cell 5: Timeout of 300 seconds exceeded executing cell

Input:
unlabeled_data = STL10(
    root=DATASET_PATH,
    split="unlabeled",
    download=True,
    transform=ContrastiveTransformations(contrast_transforms, n_views=2),
)
train_data_contrast = STL10(
    root=DATASET_PATH,
    split="train",
    download=True,
    transform=ContrastiveTransformations(contrast_transforms, n_views=2),
)

Traceback:

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 unlabeled_data = STL10(
      2     root=DATASET_PATH,
      3     split="unlabeled",
      4     download=True,
      5     transform=ContrastiveTransformations(contrast_transforms, n_views=2),
      6 )
      7 train_data_contrast = STL10(
      8     root=DATASET_PATH,
      9     split="train",
     10     download=True,
     11     transform=ContrastiveTransformations(contrast_transforms, n_views=2),
     12 )
```

**Review by akihironitta — APPROVED** [review]
LGTM!

**Comment by awaelchli** [comment]
We are getting this error now:
```
________________________ ERROR collecting test session _________________________
/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/local/lib/python3.9/dist-packages/nbval/plugin.py:146: in pytest_collect_file
    return IPyNbFile.from_parent(parent, path=Path(path))
E   TypeError: from_parent() missing 1 required keyword-only argument: 'fspath'
=============================== warnings summary ===============================
../../../usr/local/lib/python3.9/dist-packages/_pytest/config/__init__.py:1183
  /usr/local/lib/python3.9/dist-packages/_pytest/config/__init__.py:1183: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR  - TypeError: from_parent() missing 1 required keyword-only argument: '...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.19s ==========================
##[error]Bash exited with code '2'.

```


@Borda I saw that nbval comes from your personal fork. Could we try to rebase it to the latest version from upstream?

**Comment by Borda** [comment]
> I saw that nbval comes from your personal fork. Could we try to rebase it to the latest version from upstream?

resolved locally with cc593228e36f3f3015cbccc38cc85df10106d98d and open fix https://github.com/computationalmodelling/nbval/pull/196

**Pull request merged**
